version: '3'
services:
  php-app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
